framework:
  messenger:
    # Uncomment this (and the failed transport below) to send failed messages to this transport for later handling.
    # failure_transport: failed

    transports:
      async_player: '%env(MESSENGER_TRANSPORT_DSN)%/player'
      async_message: '%env(MESSENGER_TRANSPORT_DSN)%/message'
      async_pending: '%env(MESSENGER_TRANSPORT_DSN)%/pending'
      sync: 'sync://'

      # failed: 'doctrine://default?queue_name=failed'

    routing:
      App\SharedContext\Application\Bus\AsyncPlayerMessageInterface: async_player
      App\SharedContext\Application\Bus\AsyncChatMessageInterface: async_message
      App\SharedContext\Application\Bus\AsyncPendingMessageInterface: async_pending
      App\SharedContext\Application\Bus\SyncMessageInterface: sync

when@test:
  framework:
    messenger:
      transports:
        async_player: 'sync://'
        async_message: 'sync://'
        async_pending: 'sync://'
