services:

  redis:
    ports:
      - "6379:6379"

  rabbitmq:
    ports:
      - "5672:5672"
      - "15672:15672"

###> symfony/mercure-bundle ###
  mercure:
    ports:
      - "80:80"
###< symfony/mercure-bundle ###
