services:
  php:
    container_name: php
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    volumes:
      - caddy_data:/data
      - caddy_config:/config
      - ./:/app
      - ./docker/Caddyfile:/etc/frankenphp/Caddyfile:ro
    depends_on:
      - redis
      - rabbitmq
    environment:
      - SERVER_NAME=localhost, php:80
      - MERCURE_PUBLISHER_JWT_KEY=!ChangeThisMercureHubJWTSecretKey!
      - MERCURE_SUBSCRIBER_JWT_KEY=!ChangeThisMercureHubJWTSecretKey!
      - MERCURE_URL=http://php/.well-known/mercure
      - MERCURE_PUBLIC_URL=https://localhost/.well-known/mercure
      - MERCURE_JWT_SECRET=!ChangeThisMercureHubJWTSecretKey!
    extra_hosts:
      # Ensure that host.docker.internal is correctly defined on Linux
      - host.docker.internal:host-gateway
    tty: true
  
  redis:
    image: valkey/valkey:8.1.1-alpine
    volumes:
      - redis_data:/var/lib/valkey/data

  rabbitmq:
    image: rabbitmq:4-management

###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###

volumes:
  redis_data:
  caddy_data:
  caddy_config:
###> symfony/mercure-bundle ###
###< symfony/mercure-bundle ###
