parameters:

services:
  _defaults:
    autowire: true      # Automatically injects dependencies in your services.
    autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

  _instanceof:
    App\SharedContext\Application\Bus\MessageHandlerInterface:
      tags:
        - { name: messenger.message_handler }

    App\Game\Domain\Model\Entity\Level\LevelInterface:
      tags:
        - { name: app.level }

  App\:
    resource: '../src/'
    exclude:
      - '../src/**/Infrastructure/Framework/DependencyInjection/'
      - '../src/**/Domain/Model/Entity/'
      - '../src/**/Domain/Model/ValueObject/'
      - '../src/SharedContext/Infrastructure/Framework/Kernel.php'

  App\Game\Domain\Service\AvailableWorldFinder:
    arguments:
      $maxPlayersPerWorld: '%env(int:WORLD_MAX_PLAYERS)%'

  App\Game\Domain\Service\TimeoutPlayerFinder:
    arguments:
      $playerInactivityTimeout: '%env(int:PLAYER_INACTIVITY_TIMEOUT_SECS)%'

  App\Game\Application\UseCase\ConnectPlayer\ConnectPlayerHandler:
    arguments:
      $defaultLevelName: '%env(string:WORLD_DEFAULT_LEVEL)%'

  Predis\Client:
    arguments:
      $parameters:
        scheme: 'tcp'
        host: 'redis'
        port: '6379'
  Predis\ClientInterface: '@Predis\Client'

when@test:
  services:
    _defaults:
      autowire: true
      autoconfigure: true

    App\SharedContext\Infrastructure\Database\RedisDatabase:
      autowire: true
      arguments:
        $keyPrefix: 'test-'

    Predis\ClientInterface:
      alias: 'Predis\Client'
      public: true

    App\Tests\Behat\:
      resource: '../tests/Behat/*'

    App\Tests\_Helper\Stub\HubStub: ~
    Symfony\Component\Mercure\HubInterface: '@App\Tests\_Helper\Stub\HubStub'
